### ISSUE TITLE
Option to not allow importing the same photo twice

### ISSUE THREAD

**Issue by GovindasOM** [leonlatsch/Photok#115]
**Is your feature request related to a problem? Please describe.**
You can accidently import the same photo twice without noticing.

**Describe the solution you'd like**
Add option to not allow importing the same photo twice, when working with importing a lot of photos, it is easy to accidently import what has been previously imported.

**Describe alternatives you've considered**
Deleting every instance of a photo after importing it so I do not accidently import it again, but I would like Photok to just not let me import duplicates.
**Additional context**
None

**Comment by leonlatsch** [comment]
Yes, this is on purpose.
It was a design choice not to detect any duplicates.

Thats why its called "import" and not "move". Its the same reason why the originaly are not deleted.

Photok creates its own files while importing. The app won't assume a photo us the same just because it has the same name.

So this is a wont fix. Sorry.

**Comment by GovindasOM** [comment]
it could check if pixels are the same, but I understand if this feature reduces security
