### ISSUE TITLE
[Feature] Swipe videos right-left when playback & reveal android-nav buttons when video playback

### ISSUE THREAD

**Issue by SeaMorph** [leonlatsch/Photok#209]
**Is your feature request related to a problem? Please describe.**
1. When I am playing a video in Photok, I cannot swipe to the next photo/video without stopping the video playback.
2. On a phone with software android-nav buttons (back, home, tasks buttons), I have to swipe up to get the android-nav-bar; and also the nav bar hides too quickly.

**Describe the solution you'd like**
1. Change the photo/video viewer so that I can swipe to the next/prev video/photo without exiting video playback
2. Show the android-nav bar along with video playback controls for easier navigation.

**Describe alternatives you've considered**
1. & 2. I used PhotoGuard from playstore.

**Additional context**
![change-your-galaxy-s8s-navigation-bar-height-without-root 1280x600](https://user-images.githubusercontent.com/64202880/230788027-63cc3f13-798a-4366-aece-74c75f832716.jpg)

**Comment by leonlatsch** [comment]
1. This is a design choice used be many other galleries. So this won't be changed, unless many people request it.
2. This is caused because the video player is shown in fullscreen mode, wich is the standard in almost all apps. The time to hide the controls again is controlled by the operating system and cannot be influenced by the app.

I will close this as a won't fix
